FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ ./src/
COPY . .

# Initialize the model
RUN python src/add_model_bentoml.py

EXPOSE 3000

CMD ["bentoml", "serve", "src.bentoml_service:svc", "--host", "0.0.0.0", "--port", "3000"]